### ISSUE TITLE
Where is maracluster

### ISSUE THREAD

**Issue by andrewjmc** [statisticalbiotechnology/quandenser-pipeline#29]
My attempt to complete the terminated run of quandenser-pipeline (just the final maracluster consensus spectrum extraction step), has failed, still having stalled after `deserialized spectrum to precursor map`.

The command where it was interrupted was

`maracluster consensus --splitMassChargeStates --batch list.txt --clusterThresholds -10.0 --pvalThreshold -10.0 --output-folder Quandenser_output/consensus_spectra --clusterFile Quandenser_output/maracluster_extra_features/MaRaCluster.clusters_p10.tsv`

I hope that if I can simply run this command within the container, I might have all the output.

However, when I `singularity shell` into the container, the maracluster executable is not in the path. I cannot see where it is placed by `quandenser-v0-02-linux-amd64.deb` as it is not within (despite being included in the CMake compilation). I know it's there because quandenser calls it.

Thanks for your advice,

Andrew

**Comment by MatthewThe** [comment]
Unfortunately, simply running MaRaCluster from the command line will not result in exactly the same result as running it from within Quandenser, as the latter adds the precursor information obtained from the MS1 feature clustering. I'll see if there's something I can do to help you with issue #27.

FYI, the maracluster binary is not included in `quandenser-v0-02-linux-amd64.deb`, instead it links the libraries directly. The command printed in the stderr is just a placeholder for the actual function call inside the code.
